import type { PathfinderNode } from './types';
import {
    User, Search, BookOpen, GraduationCap, Sparkles,
    Flag, Compass, Target, FileText, ClipboardList,
    Star, DollarSign, Mail, Calendar, CheckSquare,
    TrendingUp, Globe, Award, Microscope, Palette,
    Music, Code, Heart, Building, PenTool, BarChart
} from 'lucide-svelte';

// Placeholder description for resources
const PLACEHOLDER_DESC = '';

// Helper: create a resource object
function res(id: string, title: string, url: string, type: NodeResource['type']) {
    return {
        id,
        title,
        description: PLACEHOLDER_DESC,
        url,
        type,
        completed: false,
    };
}

// Import resource type
import type { NodeResource } from './types';

export const nodes: PathfinderNode[] = [

    // Phase 1 — Self assessment (levels 0–1)

    {
        id: 'node-0',
        title: 'Start Here',
        description: ' Welcome node. Orients the student to the college application process as an incoming senior.',
        status: 'current',
        level: 0,
        position: 'center',
        icon: User,
        resources: [
            res('0-1', 'What Is the College Application Process?', 'https://www.google.com/search?q=step+by+step+guide+to+the+college+application+process+for+seniors', 'guide'),
            res('0-2', 'Senior Year Timeline Overview', 'https://www.google.com/search?q=college+application+timeline+and+deadlines+for+high+school+senior+year', 'article'),
            res('0-3', 'Common App vs Coalition App Explained', 'https://www.google.com/search?q=detailed+comparison+of+common+app+vs+coalition+app+for+university+admissions', 'official'),
            res('0-4', 'How Admissions Officers Read Applications', 'https://www.google.com/search?q=how+university+admissions+officers+evaluate+undergraduate+applications', 'video'),
            res('0-5', 'Understanding Holistic Review', 'https://www.google.com/search?q=what+is+holistic+review+in+college+admissions+academic+context', 'article'),
            res('0-6', 'FAFSA & Aid Overview (Early Peek)', 'https://www.google.com/search?q=how+federal+student+aid+works+and+how+to+apply+for+university', 'official'),
            res('0-7', 'Setting Up Your Application Workspace', 'https://www.google.com/search?q=best+tools+to+organize+and+track+college+applications+for+students', 'tool'),
        ],
    },

    {
        id: 'node-1',
        title: 'Know Yourself',
        description: ' Self-assessment of strengths, values, interests, and goals before building a college list.',
        status: 'upcoming',
        level: 1,
        position: 'center',
        icon: Target,
        resources: [
            res('1-1', 'College Board BigFuture Interest Inventory', 'https://www.google.com/search?q=how+to+use+college+board+bigfuture+for+career+and+major+exploration', 'tool'),
            res('1-2', 'How to Identify Your Core Strengths', 'https://www.google.com/search?q=identifying+personal+strengths+for+university+applications+and+essays', 'guide'),
            res('1-3', 'Values Clarification Exercise', 'https://www.google.com/search?q=values+assessment+exercises+for+choosing+the+right+college+environment', 'article'),
            res('1-4', 'What Do You Want From College? (Framework)', 'https://www.google.com/search?q=framework+for+evaluating+what+students+want+from+a+university+education', 'guide'),
            res('1-5', 'Career Exploration for High Schoolers', 'https://www.google.com/search?q=academic+career+exploration+tools+and+resources+for+high+school+students', 'tool'),
            res('1-6', 'Personality & Learning Style Assessments', 'https://www.google.com/search?q=best+personality+and+learning+style+tests+for+choosing+a+college+major', 'tool'),
            res('1-7', 'Journaling Prompts for College Readiness', 'https://www.google.com/search?q=reflective+journaling+prompts+for+college+readiness+and+self+discovery', 'article'),
        ],
    },

    {
        id: 'node-1-l',
        title: 'STEM Self-Audit',
        description: ' Branch for students leaning toward STEM. Evaluate math/science strengths and research interests.',
        status: 'upcoming',
        level: 1,
        position: 'left',
        icon: Microscope,
        track: 'stem',
        resources: [
            res('1l-1', 'STEM College Readiness Checklist', 'https://www.google.com/search?q=academic+checklist+for+stem+college+readiness+in+high+school', 'guide'),
            res('1l-2', 'Research vs Engineering vs Pre-Med Paths', 'https://www.google.com/search?q=differences+between+research+engineering+and+pre+med+academic+paths', 'article'),
            res('1l-3', 'AP/IB Science Course Impact on Admissions', 'https://www.google.com/search?q=how+ap+and+ib+science+curriculum+impacts+stem+university+admissions', 'article'),
            res('1l-4', 'Math Readiness Self-Assessment', 'https://www.google.com/search?q=how+to+assess+math+readiness+for+university+level+calculus+and+engineering', 'tool'),
            res('1l-5', 'Top STEM Programs to Know', 'https://www.google.com/search?q=best+undergraduate+stem+universities+and+specialized+programs', 'guide'),
            res('1l-6', 'Science Olympiad & Competition Landscape', 'https://www.google.com/search?q=impact+of+national+science+competitions+on+stem+college+admissions', 'article'),
            res('1l-7', 'How to Talk About STEM Passion in Essays', 'https://www.google.com/search?q=how+to+write+about+scientific+passion+in+university+admissions+essays', 'guide'),
        ],
    },

    {
        id: 'node-1-r',
        title: 'Humanities Self-Audit',
        description: ' Branch for students leaning toward humanities/arts. Evaluate writing, critical thinking, and creative strengths.',
        status: 'upcoming',
        level: 1,
        position: 'right',
        icon: PenTool,
        track: 'humanities',
        resources: [
            res('1r-1', 'Humanities & Social Sciences College Paths', 'https://www.google.com/search?q=academic+pathways+and+career+outcomes+for+humanities+majors', 'guide'),
            res('1r-2', 'How Writing Skills Are Evaluated in Admissions', 'https://www.google.com/search?q=how+university+admissions+evaluate+writing+and+critical+thinking+skills', 'article'),
            res('1r-3', 'Liberal Arts vs Research University Differences', 'https://www.google.com/search?q=comparison+of+liberal+arts+colleges+vs+research+universities+for+humanities', 'article'),
            res('1r-4', 'AP Humanities Courses and Their Value', 'https://www.google.com/search?q=value+of+ap+humanities+and+social+science+courses+for+university+credit', 'article'),
            res('1r-5', 'Building a Portfolio Mindset Early', 'https://www.google.com/search?q=how+to+develop+a+creative+portfolio+for+humanities+and+arts+applications', 'guide'),
            res('1r-6', 'Debate, MUN, and Humanities Competitions', 'https://www.google.com/search?q=how+debate+and+model+un+participation+benefits+college+applications', 'article'),
            res('1r-7', 'Showcasing Intellectual Curiosity in Apps', 'https://www.google.com/search?q=how+to+demonstrate+intellectual+curiosity+in+liberal+arts+admissions', 'guide'),
        ],
    },

    // Phase 2 — College list (levels 2–3)

    {
        id: 'node-2',
        title: 'Build Your College List',
        description: ' Research and categorize schools into reach, target, and safety tiers based on stats and fit.',
        status: 'upcoming',
        level: 2,
        position: 'center',
        icon: ClipboardList,
        resources: [
            res('2-1', 'How to Build a Balanced College List', 'https://www.google.com/search?q=how+to+create+a+balanced+list+of+reach+target+and+safety+colleges', 'guide'),
            res('2-2', 'Naviance / Scattergrams Explained', 'https://www.google.com/search?q=how+to+interpret+naviance+scattergrams+for+university+admissions', 'tool'),
            res('2-3', 'Niche.com School Research Tool', 'https://www.google.com/search?q=how+to+use+niche+college+search+to+find+university+cultural+fit', 'tool'),
            res('2-4', 'Understanding Acceptance Rate Data', 'https://www.google.com/search?q=analyzing+university+acceptance+rates+vs+yield+rates+for+applicants', 'article'),
            res('2-5', 'College Scorecard (Official Gov Data)', 'https://www.google.com/search?q=how+to+use+us+department+of+education+college+scorecard+effectively', 'official'),
            res('2-6', 'Reach vs Target vs Safety — Real Definitions', 'https://www.google.com/search?q=defining+reach+target+and+safety+schools+based+on+academic+stats', 'article'),
            res('2-7', 'How Many Schools Should You Apply To?', 'https://www.google.com/search?q=what+is+ the+ideal+number+of+college+applications+to+submit', 'guide'),
        ],
    },

    {
        id: 'node-2-l',
        title: 'Public University Track',
        description: ' Branch for students prioritizing in-state public universities and flagship schools.',
        status: 'upcoming',
        level: 2,
        position: 'left',
        icon: Building,
        resources: [
            res('2l-1', 'In-State vs Out-of-State Tuition Breakdown', 'https://www.google.com/search?q=how+in+state+versus+out+of+state+tuition+works+at+public+universities', 'calculator'),
            res('2l-2', 'How State Flagship Admissions Work', 'https://www.google.com/search?q=understanding+admission+requirements+for+state+flagship+universities', 'guide'),
            res('2l-3', 'UC System Application Overview', 'https://www.google.com/search?q=how+to+apply+to+the+university+of+california+system+requirements', 'official'),
            res('2l-4', 'Honors Programs at Public Universities', 'https://www.google.com/search?q=benefits+and+admissions+for+honors+colleges+at+public+universities', 'article'),
            res('2l-5', 'Merit Aid at Public Schools', 'https://www.google.com/search?q=how+to+find+merit+scholarships+at+large+public+universities', 'guide'),
            res('2l-6', 'Research Opportunities at Large Publics', 'https://www.google.com/search?q=undergraduate+research+opportunities+at+large+public+research+universities', 'article'),
            res('2l-7', 'Top Public University Programs by Major', 'https://www.google.com/search?q=best+public+university+rankings+for+specific+academic+majors', 'guide'),
        ],
    },

    {
        id: 'node-2-r',
        title: 'Private University Track',
        description: ' Branch for students targeting private colleges including LACs and research universities.',
        status: 'upcoming',
        level: 2,
        position: 'right',
        icon: Award,
        resources: [
            res('2r-1', 'Liberal Arts Colleges vs Research Universities', 'https://www.google.com/search?q=differences+between+liberal+arts+colleges+and+private+research+universities', 'article'),
            res('2r-2', 'How Need-Blind Admissions Works', 'https://www.google.com/search?q=what+is+need+blind+admissions+at+private+universities', 'guide'),
            res('2r-3', 'Common Data Set — How to Read It', 'https://www.google.com/search?q=how+to+find+and+interpret+the+common+data+set+for+colleges', 'tool'),
            res('2r-4', 'Small Class Sizes & Mentorship Culture', 'https://www.google.com/search?q=benefits+of+small+class+sizes+and+faculty+mentorship+in+college', 'article'),
            res('2r-5', 'Top Liberal Arts Colleges Overview', 'https://www.google.com/search?q=academic+rankings+and+culture+of+top+liberal+arts+colleges', 'guide'),
            res('2r-6', 'Why LACs Are Underrated for STEM', 'https://www.google.com/search?q=why+liberal+arts+colleges+are+excellent+for+stem+majors+and+research', 'article'),
            res('2r-7', 'Ivy League & Highly Selective Schools Reality Check', 'https://www.google.com/search?q=reality+of+admissions+at+ivy+league+and+highly+selective+universities', 'article'),
        ],
    },

    {
        id: 'node-3',
        title: 'Campus Fit Research',
        description: ' Go beyond rankings. Evaluate culture, size, location, programs, and student life fit.',
        status: 'upcoming',
        level: 3,
        position: 'center',
        icon: Search,
        resources: [
            res('3-1', 'Virtual Campus Tour Platforms', 'https://www.google.com/search?q=best+virtual+college+tour+platforms+for+university+research', 'tool'),
            res('3-2', 'What Questions to Ask on a College Visit', 'https://www.google.com/search?q=important+questions+for+students+to+ask+on+a+college+campus+visit', 'guide'),
            res('3-3', 'How to Use Reddit for Honest College Reviews', 'https://www.google.com/search?q=how+to+search+reddit+for+honest+student+reviews+of+universities', 'article'),
            res('3-4', 'Evaluating Student-to-Faculty Ratios', 'https://www.google.com/search?q=what+student+to+faculty+ratio+means+for+undergraduate+education+quality', 'article'),
            res('3-5', 'Greek Life, Clubs & Culture Research', 'https://www.google.com/search?q=how+to+research+college+campus+culture+greek+life+and+student+orgs', 'guide'),
            res('3-6', 'Location & Cost of Living Considerations', 'https://www.google.com/search?q=calculating+cost+of+living+for+students+in+different+college+towns', 'calculator'),
            res('3-7', 'Finding Alumni Networks on LinkedIn', 'https://www.google.com/search?q=how+to+use+linkedin+to+research+university+alumni+career+outcomes', 'tool'),
        ],
    },

    {
        id: 'node-3-l',
        title: 'Urban Campus Track',
        description: ' Branch for students who want city-based schools with internship and networking proximity.',
        status: 'upcoming',
        level: 3,
        position: 'left',
        icon: Globe,
        resources: [
            res('3l-1', 'Best Urban Colleges for Networking', 'https://www.google.com/search?q=top+universities+in+major+cities+for+internships+and+networking', 'guide'),
            res('3l-2', 'Internship Access in Major Cities', 'https://www.google.com/search?q=benefits+of+interning+while+attending+an+urban+university', 'article'),
            res('3l-3', 'Transit & Cost of Living in College Cities', 'https://www.google.com/search?q=managing+public+transit+and+urban+living+costs+as+a+college+student', 'calculator'),
            res('3l-4', 'Safety & Student Support in Urban Campuses', 'https://www.google.com/search?q=evaluating+campus+safety+and+support+at+city+based+universities', 'article'),
            res('3l-5', 'NYC, Boston, Chicago, SF — College Ecosystems', 'https://www.google.com/search?q=overview+of+college+ecosystems+in+major+us+cities+for+students', 'guide'),
            res('3l-6', 'Co-op Programs in Urban Universities', 'https://www.google.com/search?q=how+university+co+op+programs+work+at+urban+research+colleges', 'article'),
            res('3l-7', 'Part-Time Work & Campus Life Balance', 'https://www.google.com/search?q=balancing+urban+lifestyle+part+time+work+and+college+academics', 'guide'),
        ],
    },

    {
        id: 'node-3-r',
        title: 'Rural / College Town Track',
        description: ' Branch for students drawn to tight-knit campus communities and residential college life.',
        status: 'upcoming',
        level: 3,
        position: 'right',
        icon: Heart,
        resources: [
            res('3r-1', 'Benefits of Residential College Experiences', 'https://www.google.com/search?q=pros+and+cons+of+residential+college+campus+environments', 'article'),
            res('3r-2', 'Tight-Knit Community & Mental Health', 'https://www.google.com/search?q=impact+of+small+tight+knit+college+communities+on+student+wellbeing', 'guide'),
            res('3r-3', 'Research Access at Smaller Colleges', 'https://www.google.com/search?q=undergraduate+research+opportunities+at+small+rural+colleges', 'article'),
            res('3r-4', 'Campus Jobs & Work-Study at Small Schools', 'https://www.google.com/search?q=availability+of+campus+employment+at+residential+universities', 'guide'),
            res('3r-5', 'Greek Life & Traditions at Residential Colleges', 'https://www.google.com/search?q=social+traditions+and+greek+life+culture+in+college+towns', 'article'),
            res('3r-6', 'Transportation & Getting Around Without a City', 'https://www.google.com/search?q=student+transportation+options+at+rural+and+small+town+colleges', 'guide'),
            res('3r-7', 'Top Residential College Experiences Ranked', 'https://www.google.com/search?q=best+rated+residential+college+experiences+for+undergraduates', 'article'),
        ],
    },

    // Phase 3 — Testing (levels 4–5)

    {
        id: 'node-4',
        title: 'Test Strategy',
        description: ' Decide between SAT and ACT, set score targets, and plan test dates for senior year.',
        status: 'upcoming',
        level: 4,
        position: 'center',
        icon: BarChart,
        resources: [
            res('4-1', 'SAT vs ACT: Which Is Right for You?', 'https://www.google.com/search?q=how+to+choose+between+the+sat+and+act+for+college+admissions', 'guide'),
            res('4-2', 'Test-Optional Policy Tracker 2025', 'https://www.google.com/search?q=list+of+test+optional+colleges+for+2025+and+2026+applicants', 'tool'),
            res('4-3', 'How Colleges Superscore', 'https://www.google.com/search?q=how+university+superscoring+works+for+sat+and+act', 'article'),
            res('4-4', 'Senior Year Test Date Calendar', 'https://www.google.com/search?q=sat+and+act+test+dates+for+high+school+senior+year', 'official'),
            res('4-5', 'Score Targets by School Tier', 'https://www.google.com/search?q=average+sat+and+act+scores+by+university+tier+and+selectivity', 'calculator'),
            res('4-6', 'How Much Do Test Scores Actually Matter?', 'https://www.google.com/search?q=importance+of+standardized+test+scores+in+holistic+admissions+today', 'article'),
            res('4-7', 'When to Stop Testing: Diminishing Returns', 'https://www.google.com/search?q=when+to+stop+retaking+the+sat+or+act+for+college+apps', 'guide'),
        ],
    },

    {
        id: 'node-4-l',
        title: 'SAT Deep Dive',
        description: ' Branch for SAT-focused students. Study plans, official prep, and score improvement strategies.',
        status: 'upcoming',
        level: 4,
        position: 'left',
        icon: BookOpen,
        track: 'testing-sat',
        resources: [
            res('4l-1', 'Khan Academy Official SAT Prep (Free)', 'https://www.google.com/search?q=how+to+use+khan+academy+for+free+digital+sat+prep', 'tool'),
            res('4l-2', 'College Board SAT Full Practice Tests', 'https://www.google.com/search?q=where+to+find+official+digital+sat+practice+tests+full+length', 'official'),
            res('4l-3', 'Digital SAT Format Changes Explained', 'https://www.google.com/search?q=guide+to+the+new+digital+sat+format+and+scoring+changes', 'article'),
            res('4l-4', 'SAT Math Section Strategy Guide', 'https://www.google.com/search?q=strategies+for+improving+digital+sat+math+scores+university+level', 'guide'),
            res('4l-5', 'SAT Reading & Writing Breakdown', 'https://www.google.com/search?q=how+to+master+digital+sat+reading+and+writing+sections', 'guide'),
            res('4l-6', 'From 1200 to 1400: Real Student Plans', 'https://www.google.com/search?q=effective+study+schedules+for+significant+sat+score+improvement', 'article'),
            res('4l-7', 'Bluebook App — Official Digital SAT Tool', 'https://www.google.com/search?q=how+to+use+the+college+board+bluebook+app+for+sat+prep', 'tool'),
        ],
    },

    {
        id: 'node-4-r',
        title: 'ACT Deep Dive',
        description: ' Branch for ACT-focused students. Study plans, timing strategies, and science section prep.',
        status: 'upcoming',
        level: 4,
        position: 'right',
        icon: BookOpen,
        track: 'testing-act',
        resources: [
            res('4r-1', 'Official ACT Prep Guide & Practice Tests', 'https://www.google.com/search?q=best+official+act+test+prep+resources+and+practice+exams', 'official'),
            res('4r-2', 'ACT Science Section: What It Actually Tests', 'https://www.google.com/search?q=strategies+for+the+act+science+section+for+non+science+majors', 'guide'),
            res('4r-3', 'ACT Timing Strategies That Work', 'https://www.google.com/search?q=how+to+improve+pacing+and+time+management+on+the+act+exam', 'guide'),
            res('4r-4', 'ACT Math vs SAT Math Differences', 'https://www.google.com/search?q=comparison+of+math+topics+on+the+act+versus+the+sat', 'article'),
            res('4r-5', 'Free ACT Prep Resources Ranked', 'https://www.google.com/search?q=best+free+act+prep+websites+and+tools+for+students', 'tool'),
            res('4r-6', 'Raising Your ACT Composite by 3+ Points', 'https://www.google.com/search?q=proven+methods+to+increase+act+composite+score+by+multiple+points', 'article'),
            res('4r-7', 'ACT vs SAT Score Concordance Table', 'https://www.google.com/search?q=how+to+compare+act+and+sat+scores+using+concordance+tables', 'tool'),
        ],
    },

    {
        id: 'node-5',
        title: 'Test-Optional Decision',
        description: ' Evaluate whether to submit test scores for each school on your list given your score range.',
        status: 'upcoming',
        level: 5,
        position: 'center',
        icon: CheckSquare,
        resources: [
            res('5-1', 'How to Decide Whether to Submit Test Scores', 'https://www.google.com/search?q=when+to+submit+standardized+test+scores+to+test+optional+colleges', 'guide'),
            res('5-2', 'Test-Optional vs Test-Blind Difference', 'https://www.google.com/search?q=difference+between+test+optional+and+test+blind+university+admissions', 'article'),
            res('5-3', 'How Admissions Officers Use Submitted Scores', 'https://www.google.com/search?q=how+admissions+officers+evaluate+sat+scores+in+a+test+optional+world', 'article'),
            res('5-4', 'Score Range Benchmarks by School', 'https://www.google.com/search?q=how+to+find+the+middle+50+percent+sat+score+for+any+university', 'tool'),
            res('5-5', 'International Students & Test Requirements', 'https://www.google.com/search?q=standardized+testing+requirements+for+international+students+applying+to+us+colleges', 'guide'),
            res('5-6', 'Community College Transfer & Testing Rules', 'https://www.google.com/search?q=do+transfer+students+need+to+submit+sat+scores+to+universities', 'guide'),
            res('5-7', 'Making the Final Call: Checklist', 'https://www.google.com/search?q=checklist+for+deciding+whether+to+report+test+scores+on+college+apps', 'guide'),
        ],
    },

    // Phase 4 — Academics & coursework (level 6)

    {
        id: 'node-6',
        title: 'Senior Course Load',
        description: ' Finalize senior year courses. Colleges expect a rigorous senior schedule — avoid senioritis traps.',
        status: 'upcoming',
        level: 6,
        position: 'center',
        icon: GraduationCap,
        resources: [
            res('6-1', 'Why Senior Year Grades Matter More Than You Think', 'https://www.google.com/search?q=importance+of+first+semester+senior+year+grades+for+college+admissions', 'article'),
            res('6-2', 'How to Choose AP vs Dual Enrollment', 'https://www.google.com/search?q=comparison+of+ap+courses+versus+dual+enrollment+for+college+credit', 'guide'),
            res('6-3', 'What "Most Rigorous Curriculum" Means to Admissions', 'https://www.google.com/search?q=how+colleges+define+academic+rigor+in+a+high+school+course+load', 'article'),
            res('6-4', 'Recovering From a Weak Junior Year', 'https://www.google.com/search?q=how+to+show+academic+growth+in+senior+year+after+lower+junior+grades', 'guide'),
            res('6-5', 'IB Diploma in Senior Year — Pros & Cons', 'https://www.google.com/search?q=benefits+and+challenges+of+the+ib+diploma+for+university+applicants', 'article'),
            res('6-6', 'Communicating Course Changes to Colleges', 'https://www.google.com/search?q=how+to+notify+colleges+of+changes+to+your+senior+year+schedule', 'official'),
            res('6-7', 'Grade Trends: Why Upward Trajectories Help', 'https://www.google.com/search?q=how+an+upward+grade+trend+impacts+holistic+university+review', 'article'),
        ],
    },

    {
        id: 'node-6-l',
        title: 'AP / IB Strategy',
        description: ' Branch for students maximizing AP or IB course counts for selective admissions.',
        status: 'upcoming',
        level: 6,
        position: 'left',
        icon: Star,
        resources: [
            res('6l-1', 'AP Exam Score Cutoffs for College Credit', 'https://www.google.com/search?q=how+to+find+ap+score+credit+policies+for+specific+universities', 'guide'),
            res('6l-2', 'Which APs Matter Most for Your Major', 'https://www.google.com/search?q=best+ap+classes+to+take+for+specific+university+majors', 'article'),
            res('6l-3', 'IB vs AP: What Colleges Prefer', 'https://www.google.com/search?q=do+competitive+universities+prefer+ib+diploma+or+ap+classes', 'article'),
            res('6l-4', 'Balancing Multiple APs Without Burning Out', 'https://www.google.com/search?q=strategies+for+managing+a+high+rigor+ap+course+load+senior+year', 'guide'),
            res('6l-5', 'Free AP Prep — Khan Academy Courses', 'https://www.google.com/search?q=using+khan+academy+for+ap+exam+review+and+test+prep', 'tool'),
            res('6l-6', 'AP Score Sending Strategy', 'https://www.google.com/search?q=when+and+how+to+send+ap+scores+to+colleges+for+admissions', 'guide'),
            res('6l-7', 'Dual Enrollment as an AP Alternative', 'https://www.google.com/search?q=pros+and+cons+of+dual+enrollment+compared+to+ap+for+university+prep', 'article'),
        ],
    },

    {
        id: 'node-6-r',
        title: 'GPA Recovery Plan',
        description: ' Branch for students with a dip in junior year who need to show an upward trend senior year.',
        status: 'upcoming',
        level: 6,
        position: 'right',
        icon: TrendingUp,
        resources: [
            res('6r-1', 'Addressing a Low GPA in Your Application', 'https://www.google.com/search?q=how+to+explain+a+low+high+school+gpa+in+college+applications', 'guide'),
            res('6r-2', 'How Upward Grade Trends Are Evaluated', 'https://www.google.com/search?q=importance+of+upward+grade+trends+in+selective+college+admissions', 'article'),
            res('6r-3', 'Writing an Additional Info Section Explanation', 'https://www.google.com/search?q=how+to+use+the+common+app+additional+info+section+for+extenuating+circumstances', 'guide'),
            res('6r-4', 'Schools That Are More GPA-Flexible', 'https://www.google.com/search?q=finding+universities+that+look+beyond+a+lower+high+school+gpa', 'article'),
            res('6r-5', 'Study Habits Reset for Senior Year', 'https://www.google.com/search?q=improving+academic+study+habits+for+college+level+readiness', 'guide'),
            res('6r-6', 'Counselor Letter & Context Letters Strategy', 'https://www.google.com/search?q=how+high+school+counselors+provide+academic+context+for+students', 'guide'),
            res('6r-7', 'Community College Dual Enrollment as a Signal', 'https://www.google.com/search?q=using+community+college+classes+to+demonstrate+academic+improvement', 'article'),
        ],
    },

    // Phase 5 — Extracurriculars (levels 7–8)

    {
        id: 'node-7',
        title: 'EC Audit & Narrative',
        description: ' Review all extracurriculars and shape them into a coherent narrative that shows depth and leadership.',
        status: 'upcoming',
        level: 7,
        position: 'center',
        icon: Compass,
        resources: [
            res('7-1', 'How to List Extracurriculars on CommonApp', 'https://www.google.com/search?q=how+to+fill+out+the+common+app+activities+section+effectively', 'guide'),
            res('7-2', 'Quality vs Quantity in ECs', 'https://www.google.com/search?q=focusing+on+depth+of+extracurricular+involvement+for+college+apps', 'article'),
            res('7-3', 'Building a Spike vs Well-Rounded Profile', 'https://www.google.com/search?q=building+an+academic+spike+versus+a+well+rounded+student+profile', 'article'),
            res('7-4', 'How Admissions Officers Read Activity Lists', 'https://www.google.com/search?q=what+admissions+officers+look+for+in+extracurricular+activity+lists', 'article'),
            res('7-5', 'Turning Informal Activities Into Resume Items', 'https://www.google.com/search?q=how+to+list+hobbies+and+home+responsibilities+on+college+applications', 'guide'),
            res('7-6', 'The 150-Character Activity Description Formula', 'https://www.google.com/search?q=how+to+write+powerful+short+activity+descriptions+for+common+app', 'guide'),
            res('7-7', 'What Leadership Means to Colleges', 'https://www.google.com/search?q=how+to+demonstrate+leadership+impact+in+college+extracurriculars', 'article'),
        ],
    },

    {
        id: 'node-7-l',
        title: 'Research & Science ECs',
        description: ' Branch for students with lab, research, or science competition experience.',
        status: 'upcoming',
        level: 7,
        position: 'left',
        icon: Microscope,
        track: 'stem',
        resources: [
            res('7l-1', 'How to Get a Research Position as a HS Student', 'https://www.google.com/search?q=how+to+secure+a+research+internship+as+a+high+school+student', 'guide'),
            res('7l-2', 'Science Fairs That Matter (ISEF, Regeneron)', 'https://www.google.com/search?q=most+prestigious+high+school+science+competitions+for+university+apps', 'article'),
            res('7l-3', 'Writing About Research in Your Application', 'https://www.google.com/search?q=how+to+describe+scientific+research+experience+in+college+applications', 'guide'),
            res('7l-4', 'Cold Emailing Professors for Lab Opportunities', 'https://www.google.com/search?q=how+to+cold+email+university+professors+for+high+school+research', 'guide'),
            res('7l-5', 'Online Research Programs for HS Students', 'https://www.google.com/search?q=credible+online+research+mentorship+programs+for+high+schoolers', 'tool'),
            res('7l-6', 'RSI, PRIMES, and Other Elite Programs', 'https://www.google.com/search?q=most+selective+summer+stem+research+programs+for+high+school+students', 'article'),
            res('7l-7', 'How Research ECs Impact STEM Admissions', 'https://www.google.com/search?q=value+of+undergraduate+level+research+for+high+school+applicants', 'article'),
        ],
    },

    {
        id: 'node-7-r',
        title: 'Arts & Creative ECs',
        description: ' Branch for students with performing arts, visual arts, or creative writing portfolios.',
        status: 'upcoming',
        level: 7,
        position: 'right',
        icon: Palette,
        track: 'arts',
        resources: [
            res('7r-1', 'Submitting an Arts Supplement — Full Guide', 'https://www.google.com/search?q=how+to+submit+a+creative+arts+supplement+on+common+app', 'guide'),
            res('7r-2', 'When to Apply to Art-Focused vs Regular Colleges', 'https://www.google.com/search?q=choosing+between+a+bfa+degree+and+a+ba+degree+in+arts', 'article'),
            res('7r-3', 'Building a Visual Arts Portfolio for College', 'https://www.google.com/search?q=how+to+build+a+competitive+visual+arts+portfolio+for+university', 'guide'),
            res('7r-4', 'Performing Arts Audition Process Explained', 'https://www.google.com/search?q=what+to+expect+in+university+performing+arts+auditions', 'guide'),
            res('7r-5', 'Creative Writing Portfolios in College Apps', 'https://www.google.com/search?q=how+to+curate+a+creative+writing+portfolio+for+university+admissions', 'guide'),
            res('7r-6', 'Music Supplement & Recording Tips', 'https://www.google.com/search?q=recording+standards+for+university+music+performance+supplements', 'guide'),
            res('7r-7', 'How Arts Talent Affects Admissions Odds', 'https://www.google.com/search?q=how+artistic+talent+is+evaluated+at+non+arts+focused+universities', 'article'),
        ],
    },

    {
        id: 'node-8',
        title: 'Leadership & Impact',
        description: ' Identify and articulate your most meaningful leadership moments and community impact.',
        status: 'upcoming',
        level: 8,
        position: 'center',
        icon: Flag,
        resources: [
            res('8-1', 'Defining Leadership for College Applications', 'https://www.google.com/search?q=different+types+of+leadership+examples+for+college+admissions', 'guide'),
            res('8-2', 'Informal Leadership vs Formal Titles', 'https://www.google.com/search?q=how+to+show+leadership+without+having+a+formal+title+on+college+apps', 'article'),
            res('8-3', 'Community Impact Projects That Stand Out', 'https://www.google.com/search?q=how+to+start+a+meaningful+community+service+project+high+school', 'guide'),
            res('8-4', 'How to Start a Club or Initiative Senior Year', 'https://www.google.com/search?q=impact+of+starting+a+new+high+school+club+senior+year+on+apps', 'guide'),
            res('8-5', 'Service Hours vs Meaningful Volunteering', 'https://www.google.com/search?q=quality+versus+quantity+of+community+service+for+university+apps', 'article'),
            res('8-6', 'Pitching Your Impact Story Across App Sections', 'https://www.google.com/search?q=how+to+tell+a+story+of+personal+impact+throughout+college+apps', 'guide'),
            res('8-7', 'Social Entrepreneurship for High Schoolers', 'https://www.google.com/search?q=how+social+entrepreneurship+impacts+college+admissions+narrative', 'article'),
        ],
    },

    {
        id: 'node-8-l',
        title: 'Tech & Coding ECs',
        description: ' Branch for students with coding projects, hackathons, or open-source contributions.',
        status: 'upcoming',
        level: 8,
        position: 'left',
        icon: Code,
        track: 'stem',
        resources: [
            res('8l-1', 'GitHub Portfolio for College Applicants', 'https://www.google.com/search?q=how+to+use+github+to+showcase+coding+projects+for+college+apps', 'tool'),
            res('8l-2', 'Hackathon Competitions for HS Students', 'https://www.google.com/search?q=best+high+school+hackathons+for+tech+focused+applicants', 'guide'),
            res('8l-3', 'App Development as a College EC', 'https://www.google.com/search?q=how+to+describe+app+development+projects+on+university+applications', 'article'),
            res('8l-4', 'Open Source Contributions on Your App', 'https://www.google.com/search?q=value+of+open+source+contributions+for+computer+science+admissions', 'guide'),
            res('8l-5', 'Competitive Programming (USACO) Overview', 'https://www.google.com/search?q=how+competitive+programming+awards+impact+college+admissions', 'article'),
            res('8l-6', 'Coding Bootcamps & Summer Programs', 'https://www.google.com/search?q=top+summer+computer+science+programs+for+high+school+students', 'tool'),
            res('8l-7', 'How CS Admissions Reads Your Projects', 'https://www.google.com/search?q=what+top+cs+universities+look+for+in+coding+portfolios', 'article'),
        ],
    },

    {
        id: 'node-8-r',
        title: 'Advocacy & Social Impact',
        description: ' Branch for students driven by social justice, civic engagement, or nonprofit work.',
        status: 'upcoming',
        level: 8,
        position: 'right',
        icon: Heart,
        track: 'humanities',
        resources: [
            res('8r-1', 'Civic Engagement Activities That Impress Colleges', 'https://www.google.com/search?q=types+of+civic+engagement+that+strengthen+college+applications', 'guide'),
            res('8r-2', 'Starting a Nonprofit or 501c3 in High School', 'https://www.google.com/search?q=how+to+found+a+nonprofit+as+a+high+school+student+for+college+apps', 'article'),
            res('8r-3', 'Political Campaigns & Civic Internships', 'https://www.google.com/search?q=how+interning+on+political+campaigns+impacts+college+admissions', 'guide'),
            res('8r-4', 'Advocacy Writing — Op-Eds & Publications', 'https://www.google.com/search?q=how+to+publish+op+eds+and+advocacy+writing+as+a+student', 'guide'),
            res('8r-5', 'Model UN and Its Real Value in Admissions', 'https://www.google.com/search?q=real+value+of+model+un+leadership+in+university+admissions', 'article'),
            res('8r-6', 'Youth Councils & Local Government Experience', 'https://www.google.com/search?q=serving+on+youth+advisory+councils+for+college+applications', 'article'),
            res('8r-7', 'Turning Passion Into Policy — Student Stories', 'https://www.google.com/search?q=how+to+write+about+policy+advocacy+in+college+essays', 'article'),
        ],
    },

    // Phase 6 — Essays (levels 9–11)

    {
        id: 'node-9',
        title: 'CommonApp Personal Statement',
        description: ' Brainstorm, draft, and refine the 650-word personal statement — the heart of your application.',
        status: 'upcoming',
        level: 9,
        position: 'center',
        icon: PenTool,
        resources: [
            res('9-1', 'The 7 CommonApp Essay Prompts Broken Down', 'https://www.google.com/search?q=analysis+of+the+current+common+app+personal+statement+prompts', 'guide'),
            res('9-2', 'How to Choose Your Essay Topic', 'https://www.google.com/search?q=brainstorming+unique+and+meaningful+college+essay+topics', 'guide'),
            res('9-3', "Show Don't Tell: Essay Writing Principles", 'https://www.google.com/search?q=show+dont+tell+writing+examples+for+university+essays', 'article'),
            res('9-4', 'Essays That Worked — Real Examples', 'https://www.google.com/search?q=read+successful+college+essays+admitted+to+top+tier+schools', 'article'),
            res('9-5', 'The "So What?" Test for Your Essay', 'https://www.google.com/search?q=how+to+apply+the+so+what+test+to+a+college+personal+statement', 'guide'),
            res('9-6', 'Avoiding the Most Common Essay Mistakes', 'https://www.google.com/search?q=common+mistakes+to+avoid+in+undergraduate+admissions+essays', 'article'),
            res('9-7', 'Revision Checklist for Your Personal Statement', 'https://www.google.com/search?q=checklist+for+revising+and+editing+college+admissions+essays', 'tool'),
        ],
    },

    {
        id: 'node-9-l',
        title: 'Identity & Background Essays',
        description: ' Branch for students writing about cultural identity, immigrant experience, or first-gen background.',
        status: 'upcoming',
        level: 9,
        position: 'left',
        icon: User,
        resources: [
            res('9l-1', 'Writing About Your Culture Without Stereotyping', 'https://www.google.com/search?q=how+to+write+authentically+about+cultural+identity+in+college+essays', 'guide'),
            res('9l-2', 'First-Gen College Student Essay Strategies', 'https://www.google.com/search?q=unique+essay+writing+tips+for+first+generation+college+applicants', 'guide'),
            res('9l-3', 'Immigrant Experience Essays That Stand Out', 'https://www.google.com/search?q=how+to+share+immigrant+backgrounds+in+university+applications', 'article'),
            res('9l-4', 'Balancing Vulnerability and Strength in Essays', 'https://www.google.com/search?q=how+to+show+vulnerability+and+resilience+in+admissions+essays', 'guide'),
            res('9l-5', 'Multilingual Identity in College Essays', 'https://www.google.com/search?q=writing+about+being+multilingual+or+bilingual+in+college+apps', 'article'),
            res('9l-6', 'QuestBridge & First-Gen Specific Resources', 'https://www.google.com/search?q=how+to+apply+for+questbridge+scholarships+and+essays', 'official'),
            res('9l-7', 'How Diversity Statements Are Read', 'https://www.google.com/search?q=how+admissions+committees+evaluate+diversity+and+background+essays', 'article'),
        ],
    },

    {
        id: 'node-9-r',
        title: 'Overcoming Adversity Essays',
        description: ' Branch for students whose story involves hardship, challenge, or significant personal obstacles.',
        status: 'upcoming',
        level: 9,
        position: 'right',
        icon: TrendingUp,
        resources: [
            res('9r-1', 'Writing About Hardship Without Being a Victim', 'https://www.google.com/search?q=how+to+frame+adversity+as+personal+growth+in+college+essays', 'guide'),
            res('9r-2', 'Trauma-Informed Essay Writing Tips', 'https://www.google.com/search?q=safe+ways+to+share+personal+trauma+in+university+applications', 'guide'),
            res('9r-3', 'Mental Health in College Essays — Yes or No?', 'https://www.google.com/search?q=pros+and+cons+of+writing+about+mental+health+in+college+apps', 'article'),
            res('9r-4', 'Framing Challenge as Growth', 'https://www.google.com/search?q=how+to+describe+personal+obstacles+and+growth+for+admissions', 'guide'),
            res('9r-5', 'Family Hardship Essays Done Right', 'https://www.google.com/search?q=how+to+write+about+family+financial+or+personal+hardship+in+essays', 'article'),
            res('9r-6', 'Adversity vs Obstacle: Knowing the Difference', 'https://www.google.com/search?q=difference+between+common+obstacles+and+significant+adversity+in+apps', 'article'),
            res('9r-7', 'Additional Info Section for Context', 'https://www.google.com/search?q=when+to+use+the+additional+information+section+for+extenuating+circumstances', 'guide'),
        ],
    },

    {
        id: 'node-10',
        title: 'Supplement Essays',
        description: ' Research and write supplemental essays for each school: "Why Us", "Why Major", and short takes.',
        status: 'upcoming',
        level: 10,
        position: 'center',
        icon: FileText,
        resources: [
            res('10-1', '"Why This College" Essay Full Guide', 'https://www.google.com/search?q=how+to+write+a+compelling+why+this+university+supplemental+essay', 'guide'),
            res('10-2', '"Why This Major" Essay Strategy', 'https://www.google.com/search?q=how+to+explain+your+choice+of+academic+major+in+supplements', 'guide'),
            res('10-3', 'Short Answer Questions — How to Be Concise', 'https://www.google.com/search?q=tips+for+answering+short+short+college+admissions+questions', 'guide'),
            res('10-4', 'Researching Schools for Specific Supplement Details', 'https://www.google.com/search?q=how+to+research+specific+college+programs+for+why+us+essays', 'tool'),
            res('10-5', 'Activity Essay & Intellectual Interest Prompts', 'https://www.google.com/search?q=how+to+expand+on+a+single+activity+in+a+supplemental+essay', 'guide'),
            res('10-6', 'Repurposing Essays Across Schools Ethically', 'https://www.google.com/search?q=how+to+recycle+and+adapt+supplemental+essays+for+different+schools', 'article'),
            res('10-7', 'Essay Tracker Spreadsheet Template', 'https://www.google.com/search?q=best+way+to+track+multiple+supplemental+essay+deadlines', 'tool'),
        ],
    },

    {
        id: 'node-10-l',
        title: 'Ivy & T20 Supplements',
        description: ' Branch for students applying to highly selective schools with unique multi-essay requirements.',
        status: 'upcoming',
        level: 10,
        position: 'left',
        icon: Star,
        resources: [
            res('10l-1', 'Harvard Supplement Essays Breakdown', 'https://www.google.com/search?q=how+to+approach+harvard+university+supplemental+essay+prompts', 'guide'),
            res('10l-2', 'MIT Application Essays What They\'re Looking For', 'https://www.google.com/search?q=what+mit+admissions+looks+for+in+their+short+answer+essays', 'guide'),
            res('10l-3', 'Stanford Essays: Roommate Letter & Short Takes', 'https://www.google.com/search?q=how+to+write+the+stanford+roommate+essay+and+short+takes', 'guide'),
            res('10l-4', 'UChicago Uncommon Essay Strategy', 'https://www.google.com/search?q=tips+for+writing+uchicago+uncommon+supplemental+essays', 'guide'),
            res('10l-5', 'Columbia List Essays — Showing Genuine Interest', 'https://www.google.com/search?q=how+to+fill+out+the+columbia+university+list+questions+effectively', 'guide'),
            res('10l-6', 'How T20 Schools Use Supplements to Differentiate', 'https://www.google.com/search?q=why+supplemental+essays+matter+for+top+20+university+admissions', 'article'),
            res('10l-7', 'Getting Feedback on High-Stakes Essays', 'https://www.google.com/search?q=who+should+review+your+supplemental+essays+for+top+schools', 'guide'),
        ],
    },

    {
        id: 'node-10-r',
        title: 'UC Application Essays',
        description: ' Branch for students applying to the University of California system (4 PIQs instead of CommonApp).',
        status: 'upcoming',
        level: 10,
        position: 'right',
        icon: BookOpen,
        resources: [
            res('10r-1', 'UC Personal Insight Questions (PIQs) Full Guide', 'https://www.google.com/search?q=how+to+answer+university+of+california+personal+insight+questions', 'official'),
            res('10r-2', 'Choosing Which 4 PIQs to Answer', 'https://www.google.com/search?q=strategy+for+selecting+the+best+4+uc+piq+prompts+for+your+profile', 'guide'),
            res('10r-3', 'How the UC System Reads Applications', 'https://www.google.com/search?q=understanding+the+uc+comprehensive+review+admissions+process', 'article'),
            res('10r-4', 'UC GPA Calculation — Weighted vs Capped', 'https://www.google.com/search?q=how+to+calculate+your+uc+weighted+and+capped+gpa', 'calculator'),
            res('10r-5', 'UC vs CommonApp: Managing Both', 'https://www.google.com/search?q=differences+between+common+app+essays+and+uc+piqs', 'guide'),
            res('10r-6', 'UC Campus Differences Explained', 'https://www.google.com/search?q=comparison+of+academic+and+campus+culture+across+all+uc+schools', 'guide'),
            res('10r-7', 'PIQ Examples That Worked', 'https://www.google.com/search?q=successful+university+of+california+piq+examples+and+analysis', 'article'),
        ],
    },

    {
        id: 'node-11',
        title: 'Letters of Recommendation',
        description: ' Identify, approach, and brief recommenders. Provide them a brag sheet and timeline.',
        status: 'upcoming',
        level: 11,
        position: 'center',
        icon: Mail,
        resources: [
            res('11-1', 'How to Choose Your Recommenders', 'https://www.google.com/search?q=how+to+select+teachers+for+college+letters+of+recommendation', 'guide'),
            res('11-2', 'Asking for a Rec Letter — Email Templates', 'https://www.google.com/search?q=email+templates+for+requesting+a+letter+of+recommendation+from+teachers', 'guide'),
            res('11-3', 'Writing Your Own Brag Sheet', 'https://www.google.com/search?q=what+to+include+on+a+college+admissions+brag+sheet+for+teachers', 'tool'),
            res('11-4', 'What Makes a Strong Recommendation Letter', 'https://www.google.com/search?q=qualities+of+a+highly+effective+college+recommendation+letter', 'article'),
            res('11-5', 'Counselor Rec vs Teacher Rec Differences', 'https://www.google.com/search?q=difference+between+counselor+and+teacher+recommendations+in+college+apps', 'guide'),
            res('11-6', 'Optional Third Rec — When to Use It', 'https://www.google.com/search?q=when+to+submit+an+extra+letter+of+recommendation+for+college', 'article'),
            res('11-7', 'Rec Letter Deadlines & Tracker Template', 'https://www.google.com/search?q=how+to+manage+and+track+recommendation+letter+requests+for+seniors', 'tool'),
        ],
    },

    {
        id: 'node-11-l',
        title: 'Research Mentor Rec',
        description: ' Branch for STEM students getting a rec from a professor, lab mentor, or research supervisor.',
        status: 'upcoming',
        level: 11,
        position: 'left',
        icon: Microscope,
        track: 'stem',
        resources: [
            res('11l-1', 'How Research Mentor Letters Are Viewed', 'https://www.google.com/search?q=value+of+research+mentor+recommendation+letters+in+stem+admissions', 'article'),
            res('11l-2', 'Briefing Your Mentor on Your College Goals', 'https://www.google.com/search?q=how+to+prepare+a+research+mentor+to+write+a+college+recommendation', 'guide'),
            res('11l-3', 'When a Professor Rec Hurts vs Helps', 'https://www.google.com/search?q=pros+and+cons+of+submitting+a+university+professor+recommendation+in+high+school', 'article'),
            res('11l-4', 'Research Summary to Give Your Recommender', 'https://www.google.com/search?q=how+to+write+a+research+summary+for+your+recommender', 'tool'),
            res('11l-5', 'Following Up Professionally With Mentors', 'https://www.google.com/search?q=how+to+professionally+follow+up+with+recommenders+on+deadlines', 'guide'),
            res('11l-6', 'How to Waive Your Right to See the Letter', 'https://www.google.com/search?q=why+students+should+waive+their+ferpa+rights+for+recommendation+letters', 'official'),
            res('11l-7', 'Getting a Rec From an Online Program Instructor', 'https://www.google.com/search?q=asking+for+recommendations+from+online+university+course+instructors', 'guide'),
        ],
    },

    {
        id: 'node-11-r',
        title: 'Arts Portfolio Submission',
        description: ' Branch for arts students submitting a portfolio or arts supplement alongside applications.',
        status: 'upcoming',
        level: 11,
        position: 'right',
        icon: Palette,
        resources: [
            res('11r-1', 'Slideroom Portfolio Submission Guide', 'https://www.google.com/search?q=how+to+use+slideroom+to+submit+arts+portfolios+for+college', 'tool'),
            res('11r-2', 'What to Include in a Visual Arts Portfolio', 'https://www.google.com/search?q=portfolio+requirements+for+undergraduate+fine+arts+admissions', 'guide'),
            res('11r-3', 'Writing Your Artist Statement', 'https://www.google.com/search?q=how+to+write+an+artist+statement+for+university+admissions', 'guide'),
            res('11r-4', 'Music Recording Submission Standards', 'https://www.google.com/search?q=technical+standards+for+college+music+supplement+recordings', 'guide'),
            res('11r-5', 'Theatre & Dance Audition Prep', 'https://www.google.com/search?q=how+to+prepare+for+university+theatre+and+dance+auditions', 'guide'),
            res('11r-6', 'Creative Writing Portfolio Selection', 'https://www.google.com/search?q=selecting+pieces+for+a+undergraduate+creative+writing+portfolio', 'guide'),
            res('11r-7', 'Getting Your Portfolio Reviewed Before Submission', 'https://www.google.com/search?q=where+to+get+professional+feedback+on+an+arts+portfolio+before+college+apps', 'article'),
        ],
    },

    // Phase 7 — Applications (levels 12–13)

    {
        id: 'node-12',
        title: 'Application Strategy',
        description: ' Set deadlines, decide on ED/EA/RD for each school, and finalize your application calendar.',
        status: 'upcoming',
        level: 12,
        position: 'center',
        icon: Calendar,
        resources: [
            res('12-1', 'ED vs EA vs RD vs REA — Full Explainer', 'https://www.google.com/search?q=difference+between+early+decision+early+action+and+regular+decision', 'guide'),
            res('12-2', 'How to Pick Your ED School', 'https://www.google.com/search?q=how+to+decide+which+university+to+apply+to+early+decision', 'guide'),
            res('12-3', 'Application Deadline Calendar Template', 'https://www.google.com/search?q=creating+a+college+application+deadline+tracker+spreadsheet', 'tool'),
            res('12-4', 'Rolling Admissions — Apply Early Strategy', 'https://www.google.com/search?q=benefits+of+applying+to+universities+with+rolling+admissions+early', 'article'),
            res('12-5', 'CommonApp Submission Checklist', 'https://www.google.com/search?q=final+checklist+before+submitting+the+common+app', 'official'),
            res('12-6', 'Coalition App vs CommonApp — Do You Need Both?', 'https://www.google.com/search?q=pros+and+cons+of+using+coalition+versus+common+app', 'guide'),
            res('12-7', 'How Demonstrated Interest Affects Admissions', 'https://www.google.com/search?q=how+colleges+track+and+evaluate+demonstrated+interest+from+applicants', 'article'),
        ],
    },

    {
        id: 'node-12-l',
        title: 'Early Decision Strategy',
        description: ' Branch for students committing to an ED school. Understand the binding agreement and financial implications.',
        status: 'upcoming',
        level: 12,
        position: 'left',
        icon: Target,
        resources: [
            res('12l-1', 'Is ED Binding Even If Aid Is Insufficient?', 'https://www.google.com/search?q=financial+aid+loopholes+for+breaking+early+decision+agreements', 'guide'),
            res('12l-2', 'ED Acceptance Rate Boost — Real Data', 'https://www.google.com/search?q=comparing+early+decision+versus+regular+decision+acceptance+rates', 'article'),
            res('12l-3', 'How to Back Out of ED If Needed', 'https://www.google.com/search?q=valid+reasons+to+withdraw+from+a+binding+early+decision+agreement', 'official'),
            res('12l-4', 'ED II Schools and Timing', 'https://www.google.com/search?q=list+of+universities+that+offer+early+decision+2+deadlines', 'guide'),
            res('12l-5', 'Financial Aid Implications of ED', 'https://www.google.com/search?q=impact+of+applying+early+decision+on+financial+aid+packages', 'calculator'),
            res('12l-6', 'Telling Your Counselor About Your ED Choice', 'https://www.google.com/search?q=high+school+counselor+role+in+approving+early+decision+agreements', 'guide'),
            res('12l-7', 'ED Decision Day Prep', 'https://www.google.com/search?q=how+to+prepare+for+receiving+early+decision+results', 'article'),
        ],
    },

    {
        id: 'node-12-r',
        title: 'Regular Decision Planning',
        description: ' Branch for students going RD-heavy. Maximize January apps and manage submission fatigue.',
        status: 'upcoming',
        level: 12,
        position: 'right',
        icon: ClipboardList,
        resources: [
            res('12r-1', 'Managing 10+ Applications Without Burning Out', 'https://www.google.com/search?q=how+to+manage+a+high+volume+of+regular+decision+college+apps', 'guide'),
            res('12r-2', 'January 1 Deadline Survival Plan', 'https://www.google.com/search?q=strategies+for+finishing+college+apps+over+winter+break', 'guide'),
            res('12r-3', 'Prioritizing Schools in Your RD Pool', 'https://www.google.com/search?q=how+to+rank+regular+decision+schools+based+on+admission+likelihood', 'article'),
            res('12r-4', 'Waitlist Strategy From the Start', 'https://www.google.com/search?q=planning+for+college+waitlists+and+deferrals+during+rd+round', 'guide'),
            res('12r-5', 'How to Write Multiple "Why Us" Essays Fast', 'https://www.google.com/search?q=template+for+efficiently+writing+multiple+why+us+essays', 'guide'),
            res('12r-6', 'Tracking Application Portals & Checklist Items', 'https://www.google.com/search?q=best+way+to+organize+university+application+portal+logins', 'tool'),
            res('12r-7', 'RD Acceptance Rates vs ED — What to Expect', 'https://www.google.com/search?q=why+regular+decision+acceptance+rates+are+lower+than+early+decision', 'article'),
        ],
    },

    {
        id: 'node-13',
        title: 'Submit & Follow Up',
        description: ' Submit applications, confirm receipt, and manage portal logins and missing document requests.',
        status: 'upcoming',
        level: 13,
        position: 'center',
        icon: CheckSquare,
        resources: [
            res('13-1', 'Post-Submission Checklist for Every School', 'https://www.google.com/search?q=what+to+do+immediately+after+submitting+college+applications', 'guide'),
            res('13-2', 'Setting Up Application Portals', 'https://www.google.com/search?q=how+to+access+and+use+university+applicant+portals', 'tool'),
            res('13-3', 'What to Do If a Document Is Missing', 'https://www.google.com/search?q=how+to+resolve+missing+transcript+or+rec+letter+issues+in+portals', 'guide'),
            res('13-4', 'Sending Mid-Year Reports & Senior Grades', 'https://www.google.com/search?q=how+to+send+mid+year+high+school+grades+to+colleges', 'official'),
            res('13-5', 'Writing an Admissions Update Letter', 'https://www.google.com/search?q=how+to+write+a+letter+of+continued+interest+after+deferral', 'guide'),
            res('13-6', 'Demonstrated Interest After Submission', 'https://www.google.com/search?q=how+to+stay+in+touch+with+admissions+officers+post+submission', 'article'),
            res('13-7', 'Responding to Interviews & Info Sessions', 'https://www.google.com/search?q=how+to+prepare+for+university+alumni+interviews+and+questions', 'guide'),
        ],
    },

    // Phase 8 — Financial aid (level 14)

    {
        id: 'node-14',
        title: 'FAFSA & CSS Profile',
        description: ' Complete the FAFSA and CSS Profile on time. Understand EFC, need-based aid, and merit aid.',
        status: 'upcoming',
        level: 14,
        position: 'center',
        icon: DollarSign,
        resources: [
            res('14-1', 'FAFSA Step-by-Step Completion Guide', 'https://www.google.com/search?q=step+by+step+guide+to+filling+out+the+fafsa+for+new+students', 'official'),
            res('14-2', 'CSS Profile — Who Needs It & How to File', 'https://www.google.com/search?q=how+to+complete+the+college+board+css+profile+for+private+aid', 'official'),
            res('14-3', 'EFC / SAI Calculator', 'https://www.google.com/search?q=how+to+calculate+your+student+aid+index+sai+for+college', 'calculator'),
            res('14-4', 'FAFSA Opening Dates & Priority Deadlines', 'https://www.google.com/search?q=financial+aid+priority+deadlines+by+state+and+university', 'official'),
            res('14-5', 'Dependency Status — Are You Independent?', 'https://www.google.com/search?q=fafsa+dependency+status+requirements+and+definitions', 'guide'),
            res('14-6', 'How Financial Aid Packages Are Built', 'https://www.google.com/search?q=how+universities+calculate+financial+aid+award+packages', 'article'),
            res('14-7', 'Appealing a Financial Aid Award', 'https://www.google.com/search?q=how+to+write+a+financial+aid+appeal+letter+to+a+university', 'guide'),
        ],
    },

    {
        id: 'node-14-l',
        title: 'Scholarships',
        description: ' Branch for identifying and applying to external scholarships separate from school-based aid.',
        status: 'upcoming',
        level: 14,
        position: 'left',
        icon: Award,
        track: 'financial',
        resources: [
            res('14l-1', 'Scholarship Search Engines Ranked', 'https://www.google.com/search?q=best+academic+scholarship+search+engines+for+university+students', 'tool'),
            res('14l-2', 'Local vs National Scholarships — Which to Prioritize', 'https://www.google.com/search?q=how+to+find+local+high+school+scholarships+in+your+community', 'guide'),
            res('14l-3', 'Common Scholarship Essay Prompts & How to Reuse', 'https://www.google.com/search?q=strategies+for+reusing+college+essays+for+scholarship+apps', 'guide'),
            res('14l-4', 'QuestBridge National College Match', 'https://www.google.com/search?q=how+the+questbridge+national+college+match+program+works', 'official'),
            res('14l-5', 'Gates Scholarship & Coca-Cola Scholars Overview', 'https://www.google.com/search?q=how+to+apply+for+highly+competitive+national+scholarships', 'article'),
            res('14l-6', 'Scholarship Scam Red Flags', 'https://www.google.com/search?q=how+to+identify+and+avoid+financial+aid+and+scholarship+scams', 'guide'),
            res('14l-7', 'Scholarship Tracker Spreadsheet Template', 'https://www.google.com/search?q=creating+a+tracker+for+scholarship+deadlines+and+requirements', 'tool'),
        ],
    },

    {
        id: 'node-14-r',
        title: 'Net Price & Loans',
        description: ' Branch for understanding net price calculators, loan types, and realistic cost comparison.',
        status: 'upcoming',
        level: 14,
        position: 'right',
        icon: BarChart,
        track: 'financial',
        resources: [
            res('14r-1', 'Net Price Calculator — Every School Has One', 'https://www.google.com/search?q=how+to+use+university+net+price+calculators+to+estimate+costs', 'calculator'),
            res('14r-2', 'Federal vs Private Loans Explained', 'https://www.google.com/search?q=differences+between+federal+student+loans+and+private+bank+loans', 'guide'),
            res('14r-3', 'Work-Study Programs Demystified', 'https://www.google.com/search?q=how+federal+work+study+programs+operate+on+college+campuses', 'official'),
            res('14r-4', 'Subsidized vs Unsubsidized Loans', 'https://www.google.com/search?q=difference+between+subsidized+and+unsubsidized+federal+student+loans', 'article'),
            res('14r-5', 'How to Compare Financial Aid Award Letters', 'https://www.google.com/search?q=tools+for+comparing+financial+aid+packages+from+different+colleges', 'tool'),
            res('14r-6', 'ROI of College — Is the Cost Worth It?', 'https://www.google.com/search?q=calculating+return+on+investment+for+different+university+degrees', 'calculator'),
            res('14r-7', 'Income-Driven Repayment Plans Overview', 'https://www.google.com/search?q=how+income+driven+student+loan+repayment+works+after+graduation', 'guide'),
        ],
    },

    // Phase 9 — Decisions (levels 15–16)

    {
        id: 'node-15',
        title: 'Decision Day Prep',
        description: ' Compare acceptance letters, financial aid packages, and make a final school decision by May 1.',
        status: 'upcoming',
        level: 15,
        position: 'center',
        icon: Flag,
        resources: [
            res('15-1', 'How to Compare College Acceptance Letters', 'https://www.google.com/search?q=factors+to+consider+when+choosing+between+multiple+college+acceptances', 'guide'),
            res('15-2', 'Visiting Accepted Students Days (Revisit Programs)', 'https://www.google.com/search?q=what+happens+at+accepted+students+day+and+why+you+should+go', 'guide'),
            res('15-3', 'Talking to Current Students Before Deciding', 'https://www.google.com/search?q=questions+to+ask+current+students+before+committing+to+a+university', 'article'),
            res('15-4', 'Financial Aid Comparison Spreadsheet Template', 'https://www.google.com/search?q=best+excel+template+for+comparing+college+financial+aid+offers', 'tool'),
            res('15-5', 'Deferral & Waitlist — What to Do Now', 'https://www.google.com/search?q=steps+to+take+if+you+are+waitlisted+or+deferred+by+a+college', 'guide'),
            res('15-6', 'Telling Other Schools You Won\'t Attend', 'https://www.google.com/search?q=how+to+professionally+decline+a+university+acceptance+offer', 'guide'),
            res('15-7', 'Gap Year Option — When It Makes Sense', 'https://www.google.com/search?q=pros+and+cons+of+taking+a+gap+year+before+starting+university', 'article'),
        ],
    },

    {
        id: 'node-15-l',
        title: 'Waitlist Strategy',
        description: ' Branch for students waitlisted at a dream school. LOCI letters, updates, and managing hope vs reality.',
        status: 'upcoming',
        level: 15,
        position: 'left',
        icon: Search,
        resources: [
            res('15l-1', 'Letter of Continued Interest (LOCI) Template', 'https://www.google.com/search?q=how+to+write+a+letter+of+continued+interest+for+a+college+waitlist', 'guide'),
            res('15l-2', 'How Many Students Get Off Waitlists?', 'https://www.google.com/search?q=university+waitlist+acceptance+statistics+and+data', 'article'),
            res('15l-3', 'What Updates to Send After Being Waitlisted', 'https://www.google.com/search?q=types+of+academic+updates+to+send+to+colleges+while+on+waitlist', 'guide'),
            res('15l-4', 'When to Give Up on the Waitlist', 'https://www.google.com/search?q=when+to+move+on+from+a+college+waitlist+and+commit+elsewhere', 'article'),
            res('15l-5', 'Contacting the Admissions Office Professionally', 'https://www.google.com/search?q=how+to+professionaly+communicate+with+admissions+as+a+waitlisted+student', 'guide'),
            res('15l-6', 'Depositing Elsewhere While Waitlisted', 'https://www.google.com/search?q=rules+for+putting+down+a+deposit+while+on+another+schools+waitlist', 'guide'),
            res('15l-7', 'Waitlist Stories: Real Student Outcomes', 'https://www.google.com/search?q=successful+stories+of+getting+off+competitive+university+waitlists', 'article'),
        ],
    },

    {
        id: 'node-15-r',
        title: 'Gap Year Planning',
        description: ' Branch for students deferring enrollment or choosing a structured gap year instead.',
        status: 'upcoming',
        level: 15,
        position: 'right',
        icon: Globe,
        resources: [
            res('15r-1', 'How to Request a Gap Year Deferral', 'https://www.google.com/search?q=how+to+write+a+formal+gap+year+deferral+request+to+a+university', 'guide'),
            res('15r-2', 'Structured Gap Year Programs Ranked', 'https://www.google.com/search?q=best+accredited+gap+year+programs+for+university+bound+students', 'tool'),
            res('15r-3', 'AmeriCorps, City Year & Service Gap Years', 'https://www.google.com/search?q=service+based+gap+year+opportunities+like+americorps+and+city+year', 'official'),
            res('15r-4', 'International Gap Year Safety & Planning', 'https://www.google.com/search?q=planning+a+safe+and+productive+international+gap+year', 'guide'),
            res('15r-5', 'Using a Gap Year to Strengthen a Transfer App', 'https://www.google.com/search?q=how+a+gap+year+impacts+future+transfer+applications+to+universities', 'article'),
            res('15r-6', 'Financial Planning During a Gap Year', 'https://www.google.com/search?q=how+to+budget+and+fund+a+gap+year+for+students', 'guide'),
            res('15r-7', 'Gap Year Journals & Community Resources', 'https://www.google.com/search?q=best+resources+for+finding+meaningful+gap+year+activities', 'tool'),
        ],
    },

    {
        id: 'node-16',
        title: 'Committed — What\'s Next',
        description: ' You\'ve committed! Final steps: housing, orientation, scholarships to accept, and senior summer prep.',
        status: 'upcoming',
        level: 16,
        position: 'center',
        icon: Sparkles,
        resources: [
            res('16-1', 'Housing Application & Roommate Matching Tips', 'https://www.google.com/search?q=how+to+navigate+university+housing+and+roommate+selection', 'guide'),
            res('16-2', 'Orientation Prep — What to Expect', 'https://www.google.com/search?q=what+to+expect+at+undergraduate+freshman+orientation', 'guide'),
            res('16-3', 'Final Scholarship Acceptance Steps', 'https://www.google.com/search?q=how+to+claim+and+process+outside+scholarships+at+your+university', 'official'),
            res('16-4', 'Sending Final Transcripts to Your College', 'https://www.google.com/search?q=how+to+send+final+official+high+school+transcripts+to+your+college', 'official'),
            res('16-5', 'What to Do the Summer Before College', 'https://www.google.com/search?q=productive+and+fun+activities+for+the+summer+before+college+freshman+year', 'article'),
            res('16-6', 'College Packing List — What You Actually Need', 'https://www.google.com/search?q=comprehensive+dorm+room+packing+list+for+college+freshmen', 'guide'),
            res('16-7', 'Staying Connected With Your High School Network', 'https://www.google.com/search?q=how+to+maintain+professional+relationships+with+high+school+teachers', 'article'),
        ],
    },
];